name: praciar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  path_provider: ^2.1.3
  drag_and_drop_lists: ^0.4.1 
  windows_taskbar: ^1.1.2
  windows_notification: ^1.2.0
dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  msix: ^3.16.7
msix_config:
  display_name: Praciar
  publisher_display_name: Malay Patel
  identity_name: com.malay.praciar
  msix_version: 1.0.0.0
flutter: 
  uses-material-design: true

