name: praciar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  path_provider: ^2.1.3
  drag_and_drop_lists: ^0.4.1 
  windows_taskbar: ^1.1.2
  windows_notification: ^1.2.0
  flutter_responsive_helper: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  flutter_colorpicker: ^1.1.0
  intl: ^0.19.0
  humanize_duration: ^0.0.2
dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  msix: ^3.16.7
msix_config:
  display_name: Praciar
  publisher_display_name: Malay Patel
  identity_name: com.malay.praciar
  msix_version: 1.0.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

